### ISSUE TITLE
[feat] Photo Compression App Amazon S3

### ISSUE THREAD

**Issue by mrbigs** [CaliStyle/barterbender#1]

**Comment by BrandynGarske** [comment]
Dear Myles,

Thanks for updating us. I can confirm that user files will be stored on Amazon S3 from now. In case you would like to keep copies of files in your server, you can turn the "Keep files in server" setting on. This setting can be searched by using the top search bar in AdminCP.

Should you have any questions, please feel free to let us know.

Regards,
Paul

Support Staff
www.phpFox.com
Start Your Social Network Today!

**Comment by BrandynGarske** [comment]
I can confirm there are images in the Amazon S3 storage. I have uploaded a Marketplace listing and the image did upload and was shown on the Featured Image for that listing. I then went to Amazon S3 storage and see that there are multiple images in the Amazon S3/barterbender/file/pic folder, then you can see the folder locations for each function (Auctions, Yard Sales and Marketplace). 

Amazon S3 storage is working and issue is completed for now.
