### ISSUE TITLE
[feat] Auction - Search by Category 

### ISSUE THREAD

**Issue by mrbigs** [CaliStyle/barterbender#2]

**Comment by mrbigs** [comment]
Myles Golden,

A customer support staff member has replied to your support request, #397627 with the following response:

Hi Myles,


We will deploy the new custom work including merging the old customization to your live site as well.

By the way, we could not access your FTP information, could you please provide us again:

FTP:
username – cali@barterbender.com
password – CaliStyle2019
Port 21
ftp.barterbender.com


Regards,
Hanh Nguyen

We hope this response has sufficiently answered your questions. If not, please do not send another email. Instead, reply to this email or login to your account for a complete archive of all your support requests and responses.

**Comment by BrandynGarske** [comment]
Hanh, here are the FTP credentials, I have tested and can confirm they work:

FTP - 166.62.103.2
username - cali@barterbender.com
password - BarterBender23!
ftp.barterbender.com


as well as here is our cpanel:
Our cpanel is:

barterbender.com/cpanel
barterbender1
Calistyle23!


Looking forward to the completion here.

Thanks Hanh

**Comment by BrandynGarske** [comment]
Hi Myles,

Please give us a little time until tomorrow to check and then reply. I will update you soonest when we finish it.

Sorry for this delay.
Regards.
Hanh Nguyen

**Comment by BrandynGarske** [comment]
Hi Myles,

We deployed the search option and merged the custom work for Auction module. Please review and let us know if you have any feedback.

Regards,
Hanh Nguyen

**Comment by BrandynGarske** [comment]
Hanh, this does not seem to be working. For instance I went to auctions / then search \"furniture\" / and there are no search results. As you can see we have 3 current Auctions in the \"Furniture\" category.

So I dont think this is working Hanh? We wanted to be able to search in Auctions via the Categories.

Please advise, thank you Hanh

**Comment by BrandynGarske** [comment]
YouNetCo has completed the Search by Category Function - https://prnt.sc/t88uss

I feel this is a bit hard for the user to see the 3 dots so I am bouncing back to YouNetCo to see wha they can do here, below id my reply to YouNetCo:

Okay Hanh, yes I see now, thank you. So you have to click the 3 dots for the drop down? Is there anything else you can do so its easier for the user? I dont thing the user will know to click the 3 dots for the search drop down? Can we add color to the dots or can you place text there to \"click the dots for search drop down\"? Maybe just something more clear for the user to find?

Please let me know, thank you Hanh.

**Comment by BrandynGarske** [comment]
YouNetCo has added Scroll over Text over the 3 dots on the Search Bar. The text reads: "Click the dots for Advanced Search"

Does this work for Robert? 

-----

Hi Myles,

We added the tooltip text on your site, could you please check and let us know the result.

Regards,
Hanh Nguyen

**Comment by BrandynGarske** [comment]
YouNetCo is wanting to close the "Search Categories for Auctions", they have performed the custom work. In the Search Field there are 3 dots, scroll over to see tooltip text. Click on the 3 dots and drop down for advanced search populates. This is where you can choose to search via Category.
