### ISSUE TITLE
[feat] marketplace - contact 

### ISSUE THREAD

**Issue by mrbigs** [CaliStyle/barterbender#3]
Contacting through marketplace

**Comment by mrbigs** [comment]
Dear Myles,

Please accept my apology for slow reply. I can inform that when using Instant Messaging, the Contact Seller button only appear if a buyer and seller are friends together. It is necessary to note that the Instant Messages only friends to chat together. Please help us check again.

Should you have any questions, please feel free to let us know.

Regards,
Paul

Support Staff
www.phpFox.com
Start Your Social Network Today!

**Comment by BrandynGarske** [comment]
Thank you Paul. Paul, is there a way to have all registered members be friends? I have looked under Apps/Installed/Advanced Marketplace also under Apps/Installed/Advanced Members and Apps/Installed/Friend but I do not see a universal setting for all Members to be Friends?

Is there a default setting in PHPFox or a Plugin that will allow all Members to be Friends? This would allow for all Registered Members to be able to view the "Contact Seller" Button.

Thank you for your help here Paul.

**Comment by BrandynGarske** [comment]
Dear Myles,

I'm afraid that the feature you want does not exist in the script. To do what you want will require a customization in phpFox Core.

Let us know if you have any other questions.
Have a great day and thank you for your time!

Regards,
Paul

Support Staff
www.phpFox.com
Start Your Social Network Today!

**Comment by BrandynGarske** [comment]
I have reached out to YouNetCo to see if their Advanced Members Plugin has a function for all Members to be friends:

Hello, is there a way to have all registered members be friends? I have looked under Apps/Installed/Advanced Marketplace also under Apps/Installed/Advanced Members but I do not see a universal setting for all Members to be Friends?

Is there a default setting in PHPFox or a setting in Advanced Members Plugin that will allow all Members to be Friends?

Thank you for your help

**Comment by BrandynGarske** [comment]
Responce fron YouNetCo:

Hi Myles,

Thank you for contacting us.

There are no settings to configure all members to be friends. Could you please let us know the purpose of this action?

Regards,
Hanh Nguyen

**Comment by BrandynGarske** [comment]
I responded with the following: 

Yes, we are trying to have the \"Contact Seller\" Button in Marketplace to be visible for all Members. Currently you can only see the \"Contact Seller\" Button in Marketplace when you are friends with the Seller.

Do you know a way to have the \"Contact Seller\" Button be visible to all Members? If we have a Member that is not Friends with a Seller we would still like that Member to be able to purchase a listing or contact the seller.

Are there any features in Advanced Members that allows for the Members to be able to be friends by default? Or do you know how to make the \"Contact Seller\" Button visible in Marketplace to all Members?

Thank you for your help here Hanh.

**Comment by BrandynGarske** [comment]
Hi Myles,

There is a setting to allow to send message to a user not in your friend list. Please go to AdminCP > Apps > Installed > Messages > User group settings > Please select the user group on the dropbox and turn off the setting [Restrict message to friends]
https://prnt.sc/t636lh

Let me know if you still have any concerns.
Regards,
Hanh Nguyen

**Comment by BrandynGarske** [comment]
Thank you for the help here Hanh, I appreciate you helping point us in the right direction here. I have tried to go to the specific location Please go to AdminCP > Apps > Installed > Messages > User group settings > then Registered User , and there is not a setting [Restrict message to friends]? There are 6 other possible settings but none that refer to [Restrict message to friends]? I also tried Guest and there is no setting [Restrict message to friends]?

Once again thank you for you help here, if I am missing something I apologize.

Thank you Hanh

**Comment by BrandynGarske** [comment]
Okay I have found the setting in Groups to allow users to communicate even if they are not Friends. This means non-friends can now see "Contact Seller" Button in Desktop. Android and Apple Apps still do not have the "Contact Seller" Button. I have sent a request back to PHPFox to see if we need a new mobile build for this: 

------Sent to PHPFox---------

Hello Paul, seems we got the Members to be able to view the "Contact Seller" Button without being friends in Desktop. We still do not see the "Contact Seller" Button in the Apps.

Does that mean we need to request for a new mobile api build?

Thank you for the help up here Paul.

**Comment by BrandynGarske** [comment]
Got a reply back from YouNetCo (not PHP Fox yet). Ill go ahead and try to update our Social Chat app today, FTP keeps failing on that App so I might have to reinstall. Ill also look into the ChatPlus plugin recommended here by YouNetCo:

Hi Myles,

We would like to confirm that phpFox default message did not support on mobile app, so you could not see this button mobile app. In the mobile app, phpFox support you 2 solution:
1. Using Instant message: https://store.phpfox.com/apps/instant-messaging: This app already supported for mobile app.
2. Using chatplus: new phpFox solution.

Please review and let us know if you still have any concerns.
Best regards,
Hanh Nguyen

**Comment by BrandynGarske** [comment]
I have tried to update the Messages App and Social Chat App. Messages Chat worked fine and update is complete. Social Chat App seems to keep failing in Dev and Production. I have sent the following message to YouNetCo now:

Thank you Hanh. I looked at ChatPlus and seems to be a bit expensive for us, is that $799 for a 1 time license? Does it support Video Chat on the App side? 

For now I think we will try using the Instant Message. I have looked at Apps / Installed Apps / and All I see it "Messages" and "Social Chat" apps. Which app does PHPFox use for Chat Messaging here? Both apps are turned on with our build. 

Also I have tried to update the Social Chat App and the update seems to fail every time? Do you know if there is a bug or an issue with the Social Chat App? 

Thank you for the Advice here Hanh.

**Comment by BrandynGarske** [comment]
Hi Myles,

You are welcome. Please refer below information:

1. ChatPlus: We would like to confirm that it supports video chat/video group chat on the app

2. If you dont want to use Chatplus, we suggest you use Instant Message because our social chat did not support for mobile app.

3. Could you explain the issue if social chat did not work on web version.

Let us know if you still have any concerns.
Regards,
Hanh Nguyen

**Comment by BrandynGarske** [comment]
Thank you Hanh. ChatPlus looks like a great App and we might use that one in the future. For now I agree, I think we should use \"Messages\" App.

Hanh is there a difference between \"Messages\" and \"Instant Message\" app or are those the same apps you are referring too?

We are trying to have a way for our Mobile App users to communicate a purchase via the App. Currently all a User can do is leave a comment in Marketplace?

Thank you for the help Hanh
